### ISSUE TITLE
`.no-content h1` is very light

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk_admin_template#125]
For example in the Whitehall interface:

![screen shot 2016-06-17 at 10 49 17](https://cloud.githubusercontent.com/assets/121219/16147079/2ce58bcc-3479-11e6-8301-6bb5a9205bed.png)

This is `#eee` on `#fff` which feels way too light. But there's a comment in `_base.scss` that makes it sound intentional:

> Large text needs a lighter colour for balance

**Comment by gemmaleigh** [comment]
More context here: https://github.com/alphagov/govuk_admin_template/blob/401c7384a39d07d1890b84798f0459dd9010e6d7/app/assets/stylesheets/govuk_admin_template/_bootstrap_colour_overrides.scss#L8

**Comment by fofr** [comment]
This has been on my todo list for a while. Grey against white needs to be darker, while grey against black is kept as-is.

**Comment by tijmenb** [comment]
Closing, as this project is deprecated: https://github.com/alphagov/govuk_admin_template/pull/169
