### ISSUE TITLE
Gem assumes it's being used for Govuk projects

### ISSUE THREAD

**Issue by elenatanasoiu** [alphagov/govuk_admin_template#135]
I've been trying to use this template in http://www.services.buckscc.gov.uk/

However, we don't intend to send any analytics to gov uk. The template assumes that we [are](https://github.com/alphagov/govuk_admin_template/blob/master/app/views/layouts/govuk_admin_template.html.erb#L113), in this section:

```
<% unless content_for?(:exclude_analytics) %>
```

We didn't spot this until we actually tried to deploy to a production environment. It was a bit of an unpleasant surprise. 

We've had to create a tag that simulates an `:exclude_analytics` component in order to avoid sending unwanted data to gov uk. Otherwise our site crashes because there is no `GOVUK_APP_DOMAIN` environment variable defined (used [here](https://github.com/alphagov/govuk_admin_template/blob/master/app/views/layouts/govuk_admin_template.html.erb#L121))

```
<%= content_for :exclude_analytics do %>
     <%= true %>
<%= end %> 
```

Unfortunately we have several sections where this has had to be included, because we use the theme in different parts of the site (authentication, admin area). 

Wouldn't it be more efficient to remove this check:
```
<% unless content_for?(:exclude_analytics) %>
```

And replace that entire block with a default analytics block?

Or even simpler, could we disable the analytics section from the config file? 

```
# config/initializers/govuk_admin_template.rb
GovukAdminTemplate.configure do |c|
  ...
  c.analytics = false
end
```

**Comment by fofr** [comment]
The `exclude_analytics` flag was created before the config was added. I think a config flag makes sense. PRs welcome.

For context, the analytics are included by default to prevent GOV.UK admin apps from being created without any analytics, this used to be a problem when new apps were spun up. Some further debate about this can be found on the PR that initially added the `exclude_analytics` flag:

https://github.com/alphagov/govuk_admin_template/pull/80
https://github.com/alphagov/govuk_admin_template/pull/63#issuecomment-85449236

> The change that introduced the analytics (https://github.com/alphagov/govuk_admin_template/pull/59) had the intention: "This will prevent new apps from forgetting to include analytics." For this reason it'd be preferable if the template includes analytics by default and a flag can be set to disable it, perhaps `disable_google_analytics`. This would also ensure backwards compatibility.

I'd be interested to learn what you're using the gem for and how it’s worked out.

**Comment by elenatanasoiu** [comment]
We're using it for an admin section for  http://www.services.buckscc.gov.uk/. 

I'll look into adding a PR.

**Comment by elenatanasoiu** [comment]
It doesn't look like people outside the govuk organization can open pull requests. Can I get access to push my changes up?
