### ISSUE TITLE
Header wraps when the organisation name is very long

### ISSUE THREAD

**Issue by issyl0** [alphagov/govuk_admin_template#23]
In transition, using `v0.1.0` of this gem: With a user's organisation set to Department for Business, Innovation and Skills (BIS), the header wraps onto two lines because the organisation name is so long. Screenshot attached. If you require any more information, please ask.

![screen shot 2014-06-09 at 17 22 27](https://cloud.githubusercontent.com/assets/355033/3219143/8fe9a53c-eff2-11e3-8f4d-62b9485a84d1.png)

**Comment by matthewford** [comment]
Could use the org short name (BIS) instead right?

**Comment by matthewford** [comment]
vote to close this issue - it's not a issue with the admin templates, perhaps the code that links to the org in the transition app could truncate or just use abbreviations where possible to avoid taking up too much space.

https://github.com/alphagov/transition/blob/13005f698fb2e84c0c1b7f1ec508a88113d8cd34/app/helpers/application_helper.rb#L23-L29
