### ISSUE TITLE
Upgrade dummy app to Rails 4

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_admin_template#87]
The gem uses a dummy app to run tests against. Most of our publishing apps are on Rails 4 now, it probably makes sense to use an updated dummy app too.

See https://github.com/alphagov/govuk_admin_template/blob/master/govuk_admin_template.gemspec

**Comment by tijmenb** [comment]
Can't be done until all apps, including Panopticon and Publisher, are on Rails 4.X.
